name: macos

on:
  pull_request_target: {}
  workflow_dispatch: null
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos12
    steps:
      - uses: actions/checkout@v4
      - run: uname -a
      - run: file gofmt
      - run: file hello
      - run: ./hello
